/**
 * Master definition of all 20 intake sections.
 * Each section defines its key, label, icon, and structured fields.
 */

export const INTAKE_SECTIONS = [
  {
    key: "basic_info",
    label: "Basic Information",
    emoji: "👤",
    fields: [
      { key: "preferred_name", label: "Preferred Name", type: "text" },
      { key: "date_of_birth", label: "Date of Birth", type: "date" },
      { key: "ssn_last4", label: "SSN (Last 4)", type: "text" },
      { key: "gender", label: "Gender", type: "select", options: ["Male", "Female", "Non-binary", "Prefer not to say", "Other"] },
      { key: "pronouns", label: "Pronouns", type: "text" },
      { key: "ethnicity", label: "Ethnicity/Race", type: "text" },
      { key: "primary_language", label: "Primary Language", type: "text" },
      { key: "address", label: "Street Address", type: "text" },
      { key: "city", label: "City", type: "text" },
      { key: "state", label: "State", type: "text" },
      { key: "zip", label: "Zip Code", type: "text" },
      { key: "phone_cell", label: "Cell Phone", type: "text" },
      { key: "phone_home", label: "Home Phone", type: "text" },
      { key: "email", label: "Email Address", type: "text" },
      { key: "is_veteran", label: "Veteran?", type: "yesno" },
      { key: "disability_description", label: "Disability / Diagnosis", type: "textarea" },
    ],
  },
  {
    key: "vr_referral",
    label: "VR / Referral Information",
    emoji: "📋",
    fields: [
      { key: "referral_source", label: "Referred By", type: "text" },
      { key: "vr_counselor_name", label: "VR Counselor Name", type: "text" },
      { key: "vr_counselor_phone", label: "VR Counselor Phone", type: "text" },
      { key: "vr_counselor_email", label: "VR Counselor Email", type: "text" },
      { key: "vr_case_number", label: "VR Case Number", type: "text" },
      { key: "vr_office", label: "VR Office Location", type: "text" },
      { key: "service_type", label: "Service Type Authorized", type: "text" },
      { key: "authorization_start", label: "Authorization Start Date", type: "date" },
      { key: "authorization_end", label: "Authorization End Date", type: "date" },
      { key: "plan_notes", label: "IPE / Plan Notes", type: "textarea" },
    ],
  },
  {
    key: "employment_goals",
    label: "Employment Goals",
    emoji: "🎯",
    fields: [
      { key: "goal_job_title", label: "Desired Job Title(s)", type: "textarea" },
      { key: "goal_industries", label: "Preferred Industries", type: "textarea" },
      { key: "goal_work_environment", label: "Preferred Work Environment", type: "textarea" },
      { key: "goal_hours_per_week", label: "Desired Hours/Week", type: "text" },
      { key: "goal_pay_range", label: "Desired Pay Range", type: "text" },
      { key: "full_time_part_time", label: "Full-time or Part-time?", type: "select", options: ["Full-time", "Part-time", "Either"] },
      { key: "start_timeline", label: "When do you want to start working?", type: "text" },
      { key: "career_interests", label: "Career Interests / Passions", type: "textarea" },
      { key: "past_work_liked", label: "What have you liked about past work?", type: "textarea" },
      { key: "past_work_disliked", label: "What have you disliked about past work?", type: "textarea" },
    ],
  },
  {
    key: "transportation",
    label: "Transportation & Availability",
    emoji: "🚌",
    fields: [
      { key: "transportation_method", label: "How will you get to work?", type: "select", options: ["Own vehicle", "Bus/Public transit", "Ride share", "Bicycle", "Walk", "Family/Friend", "Other"] },
      { key: "has_license", label: "Valid Driver's License?", type: "yesno" },
      { key: "has_vehicle", label: "Has Own Vehicle?", type: "yesno" },
      { key: "transportation_notes", label: "Transportation Notes", type: "textarea" },
      { key: "available_monday", label: "Available Monday?", type: "yesno" },
      { key: "available_tuesday", label: "Available Tuesday?", type: "yesno" },
      { key: "available_wednesday", label: "Available Wednesday?", type: "yesno" },
      { key: "available_thursday", label: "Available Thursday?", type: "yesno" },
      { key: "available_friday", label: "Available Friday?", type: "yesno" },
      { key: "available_saturday", label: "Available Saturday?", type: "yesno" },
      { key: "available_sunday", label: "Available Sunday?", type: "yesno" },
      { key: "available_hours", label: "Available Hours (e.g. 8am–5pm)", type: "text" },
      { key: "schedule_notes", label: "Schedule Constraints / Notes", type: "textarea" },
    ],
  },
  {
    key: "documents_available",
    label: "Documents Available",
    emoji: "📁",
    fields: [
      { key: "has_resume", label: "Has Resume?", type: "yesno" },
      { key: "has_sscard", label: "Has Social Security Card?", type: "yesno" },
      { key: "has_state_id", label: "Has State ID / Driver's License?", type: "yesno" },
      { key: "has_birth_certificate", label: "Has Birth Certificate?", type: "yesno" },
      { key: "has_iep", label: "Has IEP?", type: "yesno" },
      { key: "has_vr_plan", label: "Has VR Plan (IPE)?", type: "yesno" },
      { key: "has_work_permit", label: "Has Work Permit (if minor)?", type: "yesno" },
      { key: "other_documents", label: "Other Documents Available", type: "textarea" },
      { key: "documents_notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "barriers_support",
    label: "Barriers & Support Needs",
    emoji: "🛠️",
    fields: [
      { key: "barriers_list", label: "Known Barriers to Employment", type: "textarea" },
      { key: "accommodations_needed", label: "Workplace Accommodations Needed", type: "textarea" },
      { key: "technology_barriers", label: "Technology / Computer Barriers?", type: "textarea" },
      { key: "communication_barriers", label: "Communication Barriers?", type: "textarea" },
      { key: "sensory_needs", label: "Sensory / Environmental Needs", type: "textarea" },
      { key: "job_coach_needed", label: "Job Coaching Needed?", type: "yesno" },
      { key: "support_level", label: "Support Level Needed", type: "select", options: ["Minimal", "Moderate", "Significant", "Intensive"] },
      { key: "support_notes", label: "Additional Support Notes", type: "textarea" },
    ],
  },
  {
    key: "benefits",
    label: "Benefits",
    emoji: "💰",
    fields: [
      { key: "receives_ssi", label: "Receives SSI?", type: "yesno" },
      { key: "ssi_amount", label: "SSI Monthly Amount", type: "text" },
      { key: "receives_ssdi", label: "Receives SSDI?", type: "yesno" },
      { key: "ssdi_amount", label: "SSDI Monthly Amount", type: "text" },
      { key: "receives_medicaid", label: "Receives Medicaid?", type: "yesno" },
      { key: "receives_medicare", label: "Receives Medicare?", type: "yesno" },
      { key: "receives_snap", label: "Receives SNAP/Food Stamps?", type: "yesno" },
      { key: "receives_housing_assistance", label: "Receives Housing Assistance?", type: "yesno" },
      { key: "ticket_to_work", label: "Has Ticket to Work?", type: "yesno" },
      { key: "benefits_counseling_needed", label: "Benefits Counseling Needed?", type: "yesno" },
      { key: "benefits_notes", label: "Other Benefits / Notes", type: "textarea" },
    ],
  },
  {
    key: "emergency_contact",
    label: "Emergency Contact",
    emoji: "🆘",
    fields: [
      { key: "ec_name", label: "Emergency Contact Name", type: "text" },
      { key: "ec_relationship", label: "Relationship", type: "text" },
      { key: "ec_phone", label: "Phone Number", type: "text" },
      { key: "ec_email", label: "Email Address", type: "text" },
      { key: "ec_address", label: "Address", type: "text" },
      { key: "ec2_name", label: "Secondary Contact Name", type: "text" },
      { key: "ec2_relationship", label: "Relationship", type: "text" },
      { key: "ec2_phone", label: "Phone Number", type: "text" },
    ],
  },
  {
    key: "medications",
    label: "Medications",
    emoji: "💊",
    fields: [
      { key: "takes_medications", label: "Currently Takes Medications?", type: "yesno" },
      { key: "medication_list", label: "Medication List", type: "medication_list" },
    ],
  },
  {
    key: "release_of_information",
    label: "Release of Information",
    emoji: "📝",
    fields: [
      { key: "roi_agencies", label: "Agencies / Organizations Authorized", type: "textarea" },
      { key: "roi_purpose", label: "Purpose of Release", type: "textarea" },
      { key: "roi_expiration", label: "Expiration Date", type: "date" },
      { key: "roi_signature_date", label: "Signature Date", type: "date" },
      { key: "roi_agreed", label: "Client Acknowledged?", type: "yesno" },
      { key: "roi_notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "media_release",
    label: "Media Release",
    emoji: "📸",
    fields: [
      { key: "media_release_granted", label: "Grants Permission for Photos/Video?", type: "yesno" },
      { key: "media_restrictions", label: "Any Restrictions?", type: "textarea" },
      { key: "media_signature_date", label: "Signature Date", type: "date" },
      { key: "media_notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "services_agreement",
    label: "Services Agreement",
    emoji: "🤝",
    fields: [
      { key: "agreement_understood", label: "Client Understands Services?", type: "yesno" },
      { key: "agreement_responsibilities", label: "Reviewed Client Responsibilities?", type: "yesno" },
      { key: "agreement_signature_date", label: "Signature Date", type: "date" },
      { key: "agreement_notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "application_employment",
    label: "Application for Employment",
    emoji: "📄",
    fields: [
      { key: "app_legal_name", label: "Legal Name", type: "text" },
      { key: "app_position_applying", label: "Position Applying For", type: "text" },
      { key: "app_date_available", label: "Date Available to Start", type: "date" },
      { key: "app_desired_salary", label: "Desired Salary", type: "text" },
      { key: "app_full_part", label: "Full-time or Part-time?", type: "select", options: ["Full-time", "Part-time", "Either"] },
      { key: "app_ever_employed", label: "Previously Employed?", type: "yesno" },
      { key: "app_felony", label: "Ever Convicted of a Felony?", type: "yesno" },
      { key: "app_felony_explain", label: "If yes, explain", type: "textarea" },
      { key: "app_authorized_to_work", label: "Authorized to Work in the US?", type: "yesno" },
    ],
  },
  {
    key: "education_training",
    label: "Education & Training",
    emoji: "🎓",
    fields: [
      { key: "highest_education", label: "Highest Level of Education", type: "select", options: ["Some high school", "High school diploma/GED", "Some college", "Associate degree", "Bachelor's degree", "Graduate degree", "Vocational/Trade certificate", "Other"] },
      { key: "school_name", label: "School Name", type: "text" },
      { key: "graduation_year", label: "Graduation Year", type: "text" },
      { key: "field_of_study", label: "Field of Study / Major", type: "text" },
      { key: "certifications_list", label: "Certifications / Licenses", type: "textarea" },
      { key: "vocational_training", label: "Vocational Training Programs Completed", type: "textarea" },
      { key: "additional_training", label: "Additional Training / Courses", type: "textarea" },
      { key: "education_notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "previous_employment",
    label: "Previous Employment",
    emoji: "🏢",
    fields: [
      { key: "employer1_name", label: "Employer 1 - Name", type: "text" },
      { key: "employer1_title", label: "Employer 1 - Job Title", type: "text" },
      { key: "employer1_dates", label: "Employer 1 - Dates", type: "text" },
      { key: "employer1_duties", label: "Employer 1 - Duties", type: "textarea" },
      { key: "employer1_reason_left", label: "Employer 1 - Reason for Leaving", type: "text" },
      { key: "employer2_name", label: "Employer 2 - Name", type: "text" },
      { key: "employer2_title", label: "Employer 2 - Job Title", type: "text" },
      { key: "employer2_dates", label: "Employer 2 - Dates", type: "text" },
      { key: "employer2_duties", label: "Employer 2 - Duties", type: "textarea" },
      { key: "employer2_reason_left", label: "Employer 2 - Reason for Leaving", type: "text" },
      { key: "employer3_name", label: "Employer 3 - Name", type: "text" },
      { key: "employer3_title", label: "Employer 3 - Job Title", type: "text" },
      { key: "employer3_dates", label: "Employer 3 - Dates", type: "text" },
      { key: "employer3_duties", label: "Employer 3 - Duties", type: "textarea" },
      { key: "employer3_reason_left", label: "Employer 3 - Reason for Leaving", type: "text" },
    ],
  },
  {
    key: "references",
    label: "References",
    emoji: "⭐",
    fields: [
      { key: "ref1_name", label: "Reference 1 - Name", type: "text" },
      { key: "ref1_relationship", label: "Reference 1 - Relationship", type: "text" },
      { key: "ref1_phone", label: "Reference 1 - Phone", type: "text" },
      { key: "ref1_email", label: "Reference 1 - Email", type: "text" },
      { key: "ref2_name", label: "Reference 2 - Name", type: "text" },
      { key: "ref2_relationship", label: "Reference 2 - Relationship", type: "text" },
      { key: "ref2_phone", label: "Reference 2 - Phone", type: "text" },
      { key: "ref2_email", label: "Reference 2 - Email", type: "text" },
      { key: "ref3_name", label: "Reference 3 - Name", type: "text" },
      { key: "ref3_relationship", label: "Reference 3 - Relationship", type: "text" },
      { key: "ref3_phone", label: "Reference 3 - Phone", type: "text" },
      { key: "ref3_email", label: "Reference 3 - Email", type: "text" },
    ],
  },
  {
    key: "vocational_theme",
    label: "Vocational Theme List of Twenty",
    emoji: "🌟",
    description: "Rate interest in each vocational theme area from 1 (Not interested) to 5 (Very interested).",
    fields: [
      { key: "theme_outdoor", label: "Outdoor / Nature / Animals", type: "rating" },
      { key: "theme_mechanical", label: "Mechanical / Tools / Machines", type: "rating" },
      { key: "theme_creative", label: "Creative / Art / Design", type: "rating" },
      { key: "theme_helping", label: "Helping / Caregiving / Social Services", type: "rating" },
      { key: "theme_business", label: "Business / Office / Administrative", type: "rating" },
      { key: "theme_technology", label: "Technology / Computers / IT", type: "rating" },
      { key: "theme_food", label: "Food / Culinary / Restaurant", type: "rating" },
      { key: "theme_retail", label: "Retail / Customer Service / Sales", type: "rating" },
      { key: "theme_construction", label: "Construction / Building Trades", type: "rating" },
      { key: "theme_transportation", label: "Transportation / Driving / Logistics", type: "rating" },
      { key: "theme_healthcare", label: "Healthcare / Medical / Dental", type: "rating" },
      { key: "theme_education", label: "Education / Teaching / Childcare", type: "rating" },
      { key: "theme_sports", label: "Sports / Fitness / Recreation", type: "rating" },
      { key: "theme_entertainment", label: "Entertainment / Music / Media", type: "rating" },
      { key: "theme_science", label: "Science / Research / Lab", type: "rating" },
      { key: "theme_legal", label: "Legal / Law Enforcement / Security", type: "rating" },
      { key: "theme_finance", label: "Finance / Banking / Accounting", type: "rating" },
      { key: "theme_manufacturing", label: "Manufacturing / Warehouse / Production", type: "rating" },
      { key: "theme_cleaning", label: "Cleaning / Maintenance / Janitorial", type: "rating" },
      { key: "theme_agriculture", label: "Agriculture / Farming / Landscaping", type: "rating" },
      { key: "theme_top_choices", label: "Top 3 Theme Choices (explain)", type: "textarea" },
    ],
  },
  {
    key: "social_supports",
    label: "Social Supports",
    emoji: "👥",
    fields: [
      { key: "lives_with", label: "Who do you live with?", type: "text" },
      { key: "family_support", label: "Family Support Available?", type: "yesno" },
      { key: "family_support_details", label: "Describe Family Support", type: "textarea" },
      { key: "friend_support", label: "Friend / Peer Support Available?", type: "yesno" },
      { key: "community_resources", label: "Community Resources Used", type: "textarea" },
      { key: "church_community", label: "Church / Faith Community?", type: "yesno" },
      { key: "mental_health_provider", label: "Mental Health Provider?", type: "text" },
      { key: "case_manager", label: "Case Manager / Support Coordinator?", type: "text" },
      { key: "support_notes", label: "Other Support Notes", type: "textarea" },
    ],
  },
  {
    key: "job_keeping",
    label: "Job Keeping Characteristics",
    emoji: "🔑",
    description: "Rate yourself on each characteristic from 1 (Needs Development) to 5 (Strength).",
    fields: [
      { key: "jk_punctuality", label: "Punctuality / On time", type: "rating" },
      { key: "jk_attendance", label: "Attendance / Reliability", type: "rating" },
      { key: "jk_appearance", label: "Appearance / Dress appropriately", type: "rating" },
      { key: "jk_attitude", label: "Positive Attitude", type: "rating" },
      { key: "jk_takes_direction", label: "Takes Direction Well", type: "rating" },
      { key: "jk_works_independently", label: "Works Independently", type: "rating" },
      { key: "jk_teamwork", label: "Teamwork / Gets Along with Others", type: "rating" },
      { key: "jk_communication", label: "Communication Skills", type: "rating" },
      { key: "jk_problem_solving", label: "Problem Solving", type: "rating" },
      { key: "jk_handles_stress", label: "Handles Stress / Pressure", type: "rating" },
      { key: "jk_initiative", label: "Initiative / Self-motivated", type: "rating" },
      { key: "jk_task_completion", label: "Task Completion", type: "rating" },
      { key: "jk_notes", label: "Staff Notes on Characteristics", type: "textarea" },
    ],
  },
  {
    key: "interview_prep",
    label: "Interview Preparation",
    emoji: "💼",
    fields: [
      { key: "ip_elevator_pitch", label: "Elevator Pitch (Tell me about yourself)", type: "textarea" },
      { key: "ip_strength1", label: "Strength 1", type: "text" },
      { key: "ip_strength2", label: "Strength 2", type: "text" },
      { key: "ip_strength3", label: "Strength 3", type: "text" },
      { key: "ip_weakness", label: "Area for Growth", type: "text" },
      { key: "ip_why_hire", label: "Why should we hire you?", type: "textarea" },
      { key: "ip_salary_response", label: "How would you answer salary questions?", type: "textarea" },
      { key: "ip_questions_to_ask", label: "Questions to ask the employer", type: "textarea" },
      { key: "ip_attire_ready", label: "Interview attire ready?", type: "yesno" },
      { key: "ip_practice_done", label: "Mock interview completed?", type: "yesno" },
      { key: "ip_checklist_resume", label: "Resume copies prepared?", type: "yesno" },
      { key: "ip_checklist_references", label: "Reference list prepared?", type: "yesno" },
      { key: "ip_checklist_directions", label: "Knows how to get there?", type: "yesno" },
      { key: "ip_notes", label: "Additional Notes", type: "textarea" },
    ],
  },
];

export const SECTION_STATUS_LABELS = {
  not_started: "Not Started",
  assigned: "Assigned",
  in_progress: "In Progress",
  completed: "Completed",
  reviewed: "Reviewed",
};

export const SECTION_STATUS_COLORS = {
  not_started: "bg-slate-100 text-slate-600",
  assigned: "bg-amber-100 text-amber-700",
  in_progress: "bg-blue-100 text-blue-700",
  completed: "bg-emerald-100 text-emerald-700",
  reviewed: "bg-purple-100 text-purple-700",
};

export function getSectionByKey(key) {
  return INTAKE_SECTIONS.find((s) => s.key === key);
}

export function calculateIntakeProgress(sections) {
  const total = INTAKE_SECTIONS.length;
  const completed = sections.filter(
    (s) => s.status === "completed" || s.status === "reviewed"
  ).length;
  return {
    total,
    completed,
    percent: Math.round((completed / total) * 100),
  };
}